### ISSUE TITLE
error in the time spent displayed on exiting the library 

### ISSUE THREAD

**Issue by manas-gupta-3131** [AfthabEK/Entry-Exit-DL#17]
I have identified and issue in the time spent displayed when exiting the library if the person has checked in the previous day and leaves the library after 12 am , ie the next day, I would like ot work on this issue and fix it, It would be great if you could put up this project on the hacktober fest so that I can make a contribution in it?

**Comment by AfthabEK** [comment]
Thank you for bringing the error to our attention. We would greatly appreciate it if you could create a pull request, and if you have any questions or concerns, please don't hesitate to ask.
